version: "3"
services:

  ######################
  # Servicios de almacenamiento
  ######################
    datacontainer1:
        image: dynostore/datacontainer:v1
        ports:
            - "20001:5000"
        volumes:
        - ./datacontainer/objects1/:/data/objects:rw
        environment:
        APIGATEWAY_HOST: 129.114.27.189:8095
        AUTH_HOST: 129.114.27.189:8090

