#version: "3"
services:

  ######################
  # Servicios de almacenamiento
  ######################
    datacontainer1:
        image: dynostore/datacontainer:v1
        ports:
            - "20001:5000"
        volumes:
            - ./datacontainer/objects1/:/data/objects:rw
            - ./datacontainer/code:/app
        environment:
            APIGATEWAY_HOST: 192.5.86.191:8095
            AUTH_HOST: 192.5.86.191:8090
